### ISSUE TITLE
PacBSD links to games-promo-code.co.uk

### ISSUE THREAD

**Issue by cuvtixo** [DiscoverBSD/awesome-bsd#12]
PacBSD link presently redirects to www.games-promo-code.co.uk. Some may want the entry left in the list, removing only the link.

**Comment by hovancik** [comment]
Are you still getting that redirect? I am trying on chrome and I get correct address but with cert warning

**Comment by JohnBlood** [comment]
I can get the cert warning too. The problem is that they haven't released any updates since 2017. I don't even know if the downloads work,
