### ISSUE TITLE
Add more BSD-based projects?

### ISSUE THREAD

**Issue by ondraknezour** [DiscoverBSD/awesome-bsd#3]
Having the BSD Router Project included, shouldn't there be the http://zrouter.org/ https://www.pfsense.org/ and https://opnsense.org/ projects also listed?

**Comment by hovancik** [comment]
Hey, thanks for the projects info. If you have time, you can create pull request with them, or I can add them later when I find time ;]

**Comment by hovancik** [comment]
so I added them ;]
2bf5b870cffe3f752a2c0a65a6d3334f52ff0ed7
