### ISSUE TITLE
GhostBSD no longer is based on TrueOS

### ISSUE THREAD

**Issue by thedaemon** [DiscoverBSD/awesome-bsd#35]
GhostBSD is now based on FreeBSD with OpenRC and it's own software and update stations.

**Comment by hovancik** [comment]
Hi @thedaemon , feel free to create a PR, you can edit file straight from Github:)

**Comment by thedaemon** [comment]
So your suggestion is for me to Fork this repo, just so you can press a button to automate the fix instead of typing the fix? Fine.
